/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.factura.main;

import com.factura.entities.Domicilio;
import com.factura.structure.Constantes;
import com.factura.frame.AbmAdministradoresFrame;
import com.factura.frame.AbmCategoriasFrame;
import com.factura.frame.AbmConsorciosFrame;
import com.factura.frame.AbmTextoPredeteriminadoFrame;
import com.factura.frame.nuevoTitularFrame;
import com.factura.frame.FacturaFrame;
import com.factura.frame.NotaCreditoFrame;
import com.factura.frame.NuevaCompleta2Frame;
import com.factura.frame.NuevoComprobanteFcFrame;
import com.factura.frame.VerFacturasEntreFechasFrame;
import com.factura.service.DomicilioService;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author argia
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(Constantes.getR(), Constantes.getG(), Constantes.getB()));
        this.setLocationRelativeTo(null);
        go();
//        setExtendedState(6); // this.MAXIMIZED_BOTH
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salirBtn = new javax.swing.JButton();
        nuevaBtn = new javax.swing.JButton();
        facturaBtn = new javax.swing.JButton();
        notaCreditoBtn = new javax.swing.JButton();
        nuevaCompletaBtn = new javax.swing.JButton();
        nuevaCompleta2Btn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        administradoresMnu = new javax.swing.JMenuItem();
        abmCategoriasMnu = new javax.swing.JMenuItem();
        abmClientesMnu = new javax.swing.JMenuItem();
        abmTextosMnu = new javax.swing.JMenuItem();
        abmTitularesMnu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        facturasEntreFechasMnu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        versionMnu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SISTEMA DE FACTURACION");

        salirBtn.setText("SALIR");
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });

        nuevaBtn.setText("NUEVA");
        nuevaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaBtnActionPerformed(evt);
            }
        });

        facturaBtn.setText("FACTURA");
        facturaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturaBtnActionPerformed(evt);
            }
        });

        notaCreditoBtn.setText("NOTA CRÉDITO");
        notaCreditoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaCreditoBtnActionPerformed(evt);
            }
        });

        nuevaCompletaBtn.setText("NUEVA COMPLETA");
        nuevaCompletaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaCompletaBtnActionPerformed(evt);
            }
        });

        nuevaCompleta2Btn.setText("NUEVA COMPLETA 2");
        nuevaCompleta2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaCompleta2BtnActionPerformed(evt);
            }
        });

        jMenu1.setText("ABM");

        administradoresMnu.setText("ADMINISTRADORES");
        administradoresMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administradoresMnuActionPerformed(evt);
            }
        });
        jMenu1.add(administradoresMnu);

        abmCategoriasMnu.setText("CATEGORIAS");
        abmCategoriasMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abmCategoriasMnuActionPerformed(evt);
            }
        });
        jMenu1.add(abmCategoriasMnu);

        abmClientesMnu.setText("CONSORCIOS");
        abmClientesMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abmClientesMnuActionPerformed(evt);
            }
        });
        jMenu1.add(abmClientesMnu);

        abmTextosMnu.setText("TEXTOS PREDTERMINADOS");
        abmTextosMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abmTextosMnuActionPerformed(evt);
            }
        });
        jMenu1.add(abmTextosMnu);

        abmTitularesMnu.setText("TITULARES");
        abmTitularesMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abmTitularesMnuActionPerformed(evt);
            }
        });
        jMenu1.add(abmTitularesMnu);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("INFORMES");

        facturasEntreFechasMnu.setText("FACTURAS ENTRE FECHAS");
        facturasEntreFechasMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturasEntreFechasMnuActionPerformed(evt);
            }
        });
        jMenu3.add(facturasEntreFechasMnu);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("?");

        versionMnu.setText("VERSIÓN");
        versionMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                versionMnuActionPerformed(evt);
            }
        });
        jMenu2.add(versionMnu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nuevaBtn)
                        .addGap(18, 18, 18)
                        .addComponent(facturaBtn)
                        .addGap(18, 18, 18)
                        .addComponent(notaCreditoBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                        .addComponent(salirBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nuevaCompletaBtn)
                        .addGap(18, 18, 18)
                        .addComponent(nuevaCompleta2Btn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(332, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevaCompletaBtn)
                    .addComponent(nuevaCompleta2Btn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salirBtn)
                    .addComponent(nuevaBtn)
                    .addComponent(facturaBtn)
                    .addComponent(notaCreditoBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        salir();
    }//GEN-LAST:event_salirBtnActionPerformed

    private void versionMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_versionMnuActionPerformed
        verVersionSistema();
    }//GEN-LAST:event_versionMnuActionPerformed

    private void abmTitularesMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abmTitularesMnuActionPerformed
        titulares();
    }//GEN-LAST:event_abmTitularesMnuActionPerformed

    private void abmClientesMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abmClientesMnuActionPerformed
        consorcios();
    }//GEN-LAST:event_abmClientesMnuActionPerformed

    private void abmTextosMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abmTextosMnuActionPerformed
        textos();
    }//GEN-LAST:event_abmTextosMnuActionPerformed

    private void nuevaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaBtnActionPerformed
        nuevaFc();
    }//GEN-LAST:event_nuevaBtnActionPerformed

    private void facturasEntreFechasMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturasEntreFechasMnuActionPerformed
        facturasEntreFechas();
    }//GEN-LAST:event_facturasEntreFechasMnuActionPerformed

    private void facturaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturaBtnActionPerformed
        facturas();
    }//GEN-LAST:event_facturaBtnActionPerformed

    private void notaCreditoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaCreditoBtnActionPerformed
        notasDeCredito();
    }//GEN-LAST:event_notaCreditoBtnActionPerformed

    private void administradoresMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administradoresMnuActionPerformed
        administradores();
    }//GEN-LAST:event_administradoresMnuActionPerformed

    private void nuevaCompletaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaCompletaBtnActionPerformed
        nuevaCompleta();
    }//GEN-LAST:event_nuevaCompletaBtnActionPerformed

    private void nuevaCompleta2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaCompleta2BtnActionPerformed
        nuevaCompleta2();
    }//GEN-LAST:event_nuevaCompleta2BtnActionPerformed

    private void abmCategoriasMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abmCategoriasMnuActionPerformed
        categorias();
    }//GEN-LAST:event_abmCategoriasMnuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abmCategoriasMnu;
    private javax.swing.JMenuItem abmClientesMnu;
    private javax.swing.JMenuItem abmTextosMnu;
    private javax.swing.JMenuItem abmTitularesMnu;
    private javax.swing.JMenuItem administradoresMnu;
    private javax.swing.JButton facturaBtn;
    private javax.swing.JMenuItem facturasEntreFechasMnu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton notaCreditoBtn;
    private javax.swing.JButton nuevaBtn;
    private javax.swing.JButton nuevaCompleta2Btn;
    private javax.swing.JButton nuevaCompletaBtn;
    private javax.swing.JButton salirBtn;
    private javax.swing.JMenuItem versionMnu;
    // End of variables declaration//GEN-END:variables

    private void salir() {
        int escape = JOptionPane.showConfirmDialog(null, "CONFIRME SALIR DEL SISTEMA", "Atención - salir de SISTEMA", JOptionPane.YES_NO_OPTION);
        if (escape == 0) {
            System.exit(0);
        }
    }

    private void titulares() {
        nuevoTitularFrame atf = new nuevoTitularFrame();
        atf.setVisible(true);
        this.dispose();
    }

    private void consorcios() {
        AbmConsorciosFrame atf = new AbmConsorciosFrame();
        atf.setVisible(true);
        this.dispose();
    }

    private void textos() {
        AbmTextoPredeteriminadoFrame atpf = new AbmTextoPredeteriminadoFrame();
        atpf.setVisible(true);
        this.dispose();
    }

    private void facturasEntreFechas() {
        VerFacturasEntreFechasFrame vfeff = new VerFacturasEntreFechasFrame();
        vfeff.setVisible(true);
        this.dispose();
    }

    private void nuevaFc() {
        NuevoComprobanteFcFrame ncff = new NuevoComprobanteFcFrame();
        ncff.setVisible(true);
        this.dispose();
    }

    private void verVersionSistema() {
        VersionSistemaFrame vsf = new VersionSistemaFrame();
        vsf.setVisible(true);
        this.dispose();
    }

    private void facturas() {
        FacturaFrame ff = new FacturaFrame();
        ff.setVisible(true);
        this.dispose();
    }

    private void notasDeCredito() {
        NotaCreditoFrame ncf = new NotaCreditoFrame();
        ncf.setVisible(true);
        this.dispose();
    }

    private void administradores() {
        AbmAdministradoresFrame aaf = new AbmAdministradoresFrame();
        aaf.setVisible(true);
        this.dispose();
    }

    private void nuevaCompleta() {
        
    }

    private void nuevaCompleta2() {
        NuevaCompleta2Frame nc2f = new NuevaCompleta2Frame();
        nc2f.setVisible(true);
        this.dispose();
    }

    private void categorias() {
        AbmCategoriasFrame acf = new AbmCategoriasFrame();
        acf.setVisible(true);
        this.dispose();
    }

    private void go() {
//        List<Domicilio> dm;
//        try {
//            dm = new DomicilioService().getAllDomicilios();
//        } catch (Exception ex) {
//            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }
}
