/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.factura.frame;

import com.factura.entities.Consorcio;
import com.factura.entities.Domicilio;
import com.factura.structure.Constantes;
import com.factura.main.MainFrame;
import com.factura.service.ConsorcioService;
import com.factura.util.UtilFrame;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author argia
 */
public class AbmConsorciosFrame extends javax.swing.JFrame {

    private List<Consorcio> consorcios;
    private Integer pagina = 0;
    private Integer limite = 22;

    /**
     * Creates new form AbmClientesFrame
     */
    public AbmConsorciosFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(Constantes.getR(), Constantes.getG(), Constantes.getB()));
        this.setLocationRelativeTo(null);
        limpiarCampos();
        cargarLista();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        filtroTxt = new javax.swing.JTextField();
        nuevoBtn = new javax.swing.JButton();
        modificarBtn = new javax.swing.JButton();
        inactivosBtn = new javax.swing.JButton();
        primeroBtn = new javax.swing.JButton();
        anteriorBtn = new javax.swing.JButton();
        siguienteBtn = new javax.swing.JButton();
        ultimoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ALTAS BAJAS Y MODIFICACIONES DE CONSORCIOS");

        volverBtn.setText("VOLVER");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "RAZÓN SOCIAL", "CUIT", "DOMICILIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel1.setText("CALLE:");

        filtroTxt.setText("FILTRO");

        nuevoBtn.setText("NUEVO");
        nuevoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoBtnActionPerformed(evt);
            }
        });

        modificarBtn.setText("MODIFICAR");
        modificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtnActionPerformed(evt);
            }
        });

        inactivosBtn.setText("INACTIVOS");

        primeroBtn.setText("PRIMERO");
        primeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeroBtnActionPerformed(evt);
            }
        });

        anteriorBtn.setText("ANTERIOR");
        anteriorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorBtnActionPerformed(evt);
            }
        });

        siguienteBtn.setText("SIGUIENTE");
        siguienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteBtnActionPerformed(evt);
            }
        });

        ultimoBtn.setText("ÚLTIMO");
        ultimoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nuevoBtn)
                        .addGap(18, 18, 18)
                        .addComponent(modificarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(inactivosBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(filtroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(primeroBtn)
                                .addGap(18, 18, 18)
                                .addComponent(anteriorBtn)
                                .addGap(18, 18, 18)
                                .addComponent(siguienteBtn)
                                .addGap(18, 18, 18)
                                .addComponent(ultimoBtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(filtroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primeroBtn)
                    .addComponent(anteriorBtn)
                    .addComponent(siguienteBtn)
                    .addComponent(ultimoBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBtn)
                    .addComponent(nuevoBtn)
                    .addComponent(modificarBtn)
                    .addComponent(inactivosBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void nuevoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoBtnActionPerformed
        nuevo();
    }//GEN-LAST:event_nuevoBtnActionPerformed

    private void modificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnActionPerformed
        modificar();
    }//GEN-LAST:event_modificarBtnActionPerformed

    private void primeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeroBtnActionPerformed
        primero();
    }//GEN-LAST:event_primeroBtnActionPerformed

    private void anteriorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorBtnActionPerformed
        anterior();
    }//GEN-LAST:event_anteriorBtnActionPerformed

    private void siguienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteBtnActionPerformed
        siguiente();
    }//GEN-LAST:event_siguienteBtnActionPerformed

    private void ultimoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimoBtnActionPerformed
        ultimo();
    }//GEN-LAST:event_ultimoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbmConsorciosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbmConsorciosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbmConsorciosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbmConsorciosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbmConsorciosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anteriorBtn;
    private javax.swing.JTextField filtroTxt;
    private javax.swing.JButton inactivosBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarBtn;
    private javax.swing.JButton nuevoBtn;
    private javax.swing.JButton primeroBtn;
    private javax.swing.JButton siguienteBtn;
    private javax.swing.JTable tabla;
    private javax.swing.JButton ultimoBtn;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void volver() {
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }

    private void limpiarCampos() {
        filtroTxt.setText("");
    }

    private void cargarLista() {
        consorcios = null;
        try {
            consorcios = new ConsorcioService().getAllConsorciosActivasByPagina(pagina, limite);
        } catch (Exception ex) {
//            Logger.getLogger(AbmConsorciosFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "TABLA VACIA");
            return;
        }
//        llenarTabla();
    }

    private void llenarTabla() {
        UtilFrame.limpiarTabla(tabla);
        if (consorcios != null && !consorcios.isEmpty()) {
            DefaultTableModel tbl = (DefaultTableModel) tabla.getModel();
            for (Consorcio co : consorcios) {
                Object o[] = new Object[4];
                o[0] = co.getCodigo().toString();
                o[1] = co.getNombre();
                Domicilio dm = co.getDomicilio();
                String calle = dm.getCalle();
                String numero = dm.getNumero();
                o[2] = co.getCuit();
                o[3] = calle + " " + numero;
                tbl.addRow(o);
            }
            tabla.setModel(tbl);
        }
    }

    private void nuevo() {
        NuevoConsorcioFrame ncf = new NuevoConsorcioFrame();
        ncf.setVisible(true);
        this.dispose();
    }

    private void modificar() {
        int row = tabla.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(this, "SELECCIONE UN CONSORCIO PARA MODIFICAR");
            return;
        }
        Consorcio co = consorcios.get(row);
        
    }

    private void primero() {
        pagina = 0;
        consorcios = null;
            try {
                consorcios = new ConsorcioService().getAllConsorciosActivasByPagina(pagina, limite);
            } catch (Exception ex) {
                Logger.getLogger(AbmConsorciosFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (consorcios != null && !consorcios.isEmpty()) {
                llenarTabla();
                System.out.println(pagina);
            }
    }

    private void anterior() {
        String filtro = filtroTxt.getText();
        if (filtro.isEmpty()) {
            pagina -= limite;
            if (pagina < 0) {
                pagina = 0;
            }
            consorcios = null;
            try {
                consorcios = new ConsorcioService().getAllConsorciosActivasByPagina(pagina, limite);
            } catch (Exception ex) {
                Logger.getLogger(AbmConsorciosFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (consorcios != null && !consorcios.isEmpty()) {
                llenarTabla();
                System.out.println(pagina);
            }
        }
    }

    private void siguiente() {
        String filtro = filtroTxt.getText();
        Boolean hay = false;
        if (filtro.isEmpty()) {
            pagina += limite;
            consorcios = null;
            try {
                consorcios = new ConsorcioService().getAllConsorciosActivasByPagina(pagina, limite);
            } catch (Exception ex) {
                Logger.getLogger(AbmConsorciosFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (consorcios != null && !consorcios.isEmpty()) {
                llenarTabla();
                System.out.println(pagina);
            } else {
                pagina -= limite;
//                llenarTabla();
                System.out.println(pagina);
            }
        }
    }

    private void ultimo() {
        String filtro = filtroTxt.getText();
        Boolean hay = false;
        if (filtro.isEmpty()) {
            pagina =0;
            consorcios = null;
            try {
                consorcios = new ConsorcioService().getConsorciosByUltimaPagina(pagina, limite);
            } catch (Exception ex) {
                Logger.getLogger(AbmConsorciosFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (consorcios != null && !consorcios.isEmpty()) {
                llenarTabla();
                System.out.println(pagina);
            } else {
                pagina -= limite;
//                llenarTabla();
                System.out.println(pagina);
            }
        }
    }
}
