/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.factura.frame;

import com.factura.entities.Administrador;
import com.factura.entities.Domicilio;
import com.factura.structure.Constantes;
import com.factura.main.MainFrame;
import com.factura.service.AdministradorService;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author argia
 */
public class ModificarAdministradorFrame extends javax.swing.JFrame {

    private Administrador adm;

    /**
     * Creates new form NuevaFrame
     *
     * @param adm
     */
    public ModificarAdministradorFrame(Administrador adm) {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(Constantes.getR(), Constantes.getG(), Constantes.getB()));
        this.setLocationRelativeTo(null);
        this.adm = adm;
        llenarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mesCorrienteChk = new javax.swing.JCheckBox();
        nombreTxt = new javax.swing.JTextField();
        codigoPostalTxt = new javax.swing.JTextField();
        pisoDtoTxt = new javax.swing.JTextField();
        numeroTxt = new javax.swing.JTextField();
        cuitTxt = new javax.swing.JTextField();
        calleTxt = new javax.swing.JTextField();
        codigoTxt = new javax.swing.JTextField();
        localidadTxt = new javax.swing.JTextField();
        provinciaTxt = new javax.swing.JTextField();
        telefonoTxt = new javax.swing.JTextField();
        mailTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        observacionesTxt = new javax.swing.JTextField();
        grabarBtn = new javax.swing.JButton();
        activoChk = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MODIFICAR ADMINISTRADOR");

        volverBtn.setText("VOLVER");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("CÓDIGO:");

        jLabel2.setText("NOMBRE:");

        jLabel3.setText("CUIT:");

        jLabel4.setText("CALLE:");

        jLabel5.setText("NUMERO:");

        jLabel6.setText("PISO DTO.:");

        jLabel7.setText("CÓDIGO POSTAL:");

        jLabel8.setText("LOCALIDAD:");

        jLabel9.setText("PROVINCIA:");

        jLabel10.setText("TELÉFONO:");

        jLabel11.setText("MAIL:");

        mesCorrienteChk.setText("PAGA MES CORRIENTE");

        nombreTxt.setText("NOMBRE");

        codigoPostalTxt.setText("COD POSTAL");

        pisoDtoTxt.setText("PISO DTO");

        numeroTxt.setText("NUMERO");

        cuitTxt.setText("CUIT");

        calleTxt.setText("CALLE");

        codigoTxt.setText("CODIGO");

        localidadTxt.setText("LOCALIDAD");

        provinciaTxt.setText("PROVINCIA");

        telefonoTxt.setText("TELEFONO");

        mailTxt.setText("MAIL");

        jLabel12.setText("OBSERVACIONES:");

        observacionesTxt.setText("OBS");

        grabarBtn.setText("GRABAR");
        grabarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabarBtnActionPerformed(evt);
            }
        });

        activoChk.setText("ACTIVO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(nombreTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(calleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cuitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(117, 117, 117)
                                        .addComponent(activoChk))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(186, 186, 186)
                                .addComponent(mesCorrienteChk))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(localidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(codigoPostalTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                        .addComponent(pisoDtoTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(numeroTxt, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(observacionesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(telefonoTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(provinciaTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))))
                        .addGap(0, 98, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(grabarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mesCorrienteChk)
                    .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cuitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activoChk))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(calleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(numeroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pisoDtoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(codigoPostalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(localidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(provinciaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(telefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(mailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(observacionesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBtn)
                    .addComponent(grabarBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void grabarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabarBtnActionPerformed
        grabar();
    }//GEN-LAST:event_grabarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarAdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarAdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarAdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarAdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarAdministradorFrame(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox activoChk;
    private javax.swing.JTextField calleTxt;
    private javax.swing.JTextField codigoPostalTxt;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JTextField cuitTxt;
    private javax.swing.JButton grabarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField localidadTxt;
    private javax.swing.JTextField mailTxt;
    private javax.swing.JCheckBox mesCorrienteChk;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextField numeroTxt;
    private javax.swing.JTextField observacionesTxt;
    private javax.swing.JTextField pisoDtoTxt;
    private javax.swing.JTextField provinciaTxt;
    private javax.swing.JTextField telefonoTxt;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void volver() {
        AbmAdministradoresFrame mf = new AbmAdministradoresFrame();
        mf.setVisible(true);
        this.dispose();
    }

    private void grabar() {
        if (validar()) {
//            Administrador adm = new Administrador();
            if (activoChk.isSelected()) {
                adm.setActivo(true);
            } else {
                adm.setActivo(false);
            }
            try {
                Integer codigo = Integer.valueOf(codigoTxt.getText());
                adm.setCodigo(codigo);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "ERROR EN CODIGO");
                codigoTxt.requestFocus();
            }
            adm.setCuit(cuitTxt.getText());
            Domicilio dm = adm.getDomicilio();
            dm.setCalle(calleTxt.getText());
            dm.setCodigoPostal(codigoPostalTxt.getText());
            dm.setLocalidad(localidadTxt.getText());
            dm.setNumero(numeroTxt.getText());
            dm.setPisoDto(pisoDtoTxt.getText());
            dm.setProvincia(provinciaTxt.getText());
            adm.setDomicilio(dm);
            adm.setMail(mailTxt.getText());
            adm.setNombre(nombreTxt.getText());
            adm.setObservaciones(observacionesTxt.getText());
            if (mesCorrienteChk.isSelected()) {
                adm.setPagaMesCorriente(true);
            } else {
                adm.setPagaMesCorriente(false);
            }
            adm.setTelefono(telefonoTxt.getText());
            try {
                new AdministradorService().updateAdministrador(adm);
            } catch (Exception ex) {
                Logger.getLogger(ModificarAdministradorFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "ERROR GRABANDO ADMINISTRADOR");
                nombreTxt.requestFocus();
                return;
            }
            JOptionPane.showMessageDialog(this, "GRABADO CORRECTAMENTE");
            volver();
        }
    }

    private boolean validar() {
        int largo = cuitTxt.getText().length();
        if (largo > 0) {
            if (largo > 13) {
                JOptionPane.showMessageDialog(this, "ERROR LARGO CUIT");
                cuitTxt.requestFocus();
                return false;
            }
            if (largo < 13) {
                JOptionPane.showMessageDialog(this, "ERROR LARGO CUIT");
                cuitTxt.requestFocus();
                return false;
            }
            String str1 = cuitTxt.getText().substring(2, 3);//20-14255320-2
            String str2 = cuitTxt.getText().substring(11, 12);//1234567890123
            if (!str1.equals("-")) {
                JOptionPane.showMessageDialog(this, "DEBE COLOCAR GUIONES A LA CUIT");
                cuitTxt.requestFocus();
                return false;
            }
            if (!str2.equals("-")) {
                JOptionPane.showMessageDialog(this, "DEBE COLOCAR GUIONES A LA CUIT");
                cuitTxt.requestFocus();
                return false;
            }
        }

        if (nombreTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR UN NOMBRE");
            nombreTxt.requestFocus();
            return false;
        }
        return true;
    }

    private void llenarCampos() {
        mesCorrienteChk.setVisible(false);
        Integer codigo = adm.getCodigo();
        codigoTxt.setText(codigo.toString());
        codigoTxt.setEditable(false);
        nombreTxt.setText(adm.getNombre());
        nombreTxt.requestFocus();
        Domicilio dm = adm.getDomicilio();
        calleTxt.setText(dm.getCalle());
        codigoPostalTxt.setText(dm.getCodigoPostal());
        cuitTxt.setText(adm.getCuit());
        localidadTxt.setText(dm.getLocalidad());
        mailTxt.setText(adm.getMail());
        if (adm.getPagaMesCorriente()) {
            mesCorrienteChk.setSelected(true);
        } else {
            mesCorrienteChk.setSelected(false);
        }
        if (adm.getActivo()) {
            activoChk.setSelected(true);
        } else {
            activoChk.setSelected(false);
        }
        numeroTxt.setText(dm.getNumero());
        observacionesTxt.setText(adm.getObservaciones());
        pisoDtoTxt.setText(dm.getPisoDto());
        provinciaTxt.setText(dm.getProvincia());
        telefonoTxt.setText(adm.getTelefono());
    }

}
